### ISSUE TITLE
compatible Nutrition

### ISSUE THREAD

**Issue by axin0452** [canitzp/FeederHelmet#11]
It does not increase nutritional value when it is eaten automatically.

**Comment by WesCook** [comment]
Nutrition mod author here.  I marked this as closed on my side because I believe it's best implemented on this side by emulating the appropriate event.

* https://github.com/WesCook/Nutrition/issues/175
* https://github.com/WesCook/Nutrition/issues/159#issuecomment-482754407

But let me know if you run into any issues.

**Comment by canitzp** [comment]
So it works when I fire the finish event after I called the item method?

**Comment by WesCook** [comment]
I haven't tested, but that would be my guess!

**Comment by canitzp** [comment]
@WesCook I fixed this by adding the finish event (I also added the start event), but only in the latest mc version, 1.14.x. I probably won't fix older version, if it isn't mandatory. How are your plans of updating to 1.14?

**Comment by Jecvay** [comment]
as sponge claimed 1.12.2 as a long term support version these days,
can you fixed 1.12.2 for a more widely effect ?

**Comment by WesCook** [comment]
>How are your plans of updating to 1.14?

Haven't even started looking into it yet!  It's on the docket, though.

**Comment by canitzp** [comment]
I'll try to create a 1.12.2 fixed version, but idk if I can

**Comment by Jecvay** [comment]
thanks

**Comment by canitzp** [comment]
@Jecvay @WesCook FeederHelmet-1.4.1 is now uploaded to curseforge. This is a 1.12.x version with the two events, but I haven't tested if it actually fixes the issue
