### ISSUE TITLE
Over-eating

### ISSUE THREAD

**Issue by TookUrSweetRoll** [canitzp/FeederHelmet#15]
Switching to spectator mode continually eats.

**Comment by canitzp** [comment]
Why would you switch to spectator mode when playing survival? I'll fix it of course

**Comment by TookUrSweetRoll** [comment]
Thank you.

**Comment by canitzp** [comment]
I have tested this with the latest version for 1.15.2 (Feeder Helmet 1.7.0) and I can't confirm this behavior.
Can you give me some more information about your environment? Like Minecraft version, mod version and so on
