### ISSUE TITLE
Auto Feeder Helmet and MMDLib conflict.

### ISSUE THREAD

**Issue by ghost** [canitzp/FeederHelmet#19]
[crash-2021-03-21_21.53.57-client.txt](https://github.com/canitzp/FeederHelmet/files/6182590/crash-2021-03-21_21.53.57-client.txt)
There is a crash report, my Minecraft version is 1.12.2 , Forge version is 2854.
I deleted one of the Auto Feeder Helmet or MMDLib, the problem has solved.
Can you fix it? then, I have reported it in MMDLib

**Comment by canitzp** [comment]
We discuss it over at MMDLibs issue tracker: https://github.com/MinecraftModDevelopmentMods/MMDLib/issues/68
