### ISSUE TITLE
[1.16.5] Feeder helmet module no longer able to apply.

### ISSUE THREAD

**Issue by ProsperCraft** [canitzp/FeederHelmet#20]
FeederHelmet-1.10.1

Unable to apply to any helms, even vanilla helms.

**Comment by canitzp** [comment]
Thanks for the report, I'll look into it within 24 hours.

**Comment by canitzp** [comment]
@ProsperCraft I cannot exactly reprosude what you told, but there was a strange crafting bug.
Whenever you try to craft any helmet with the feeder module, it works fine when you put it into the crafting grid, but it applies the feeding module to the helmet, even when you just pick up the helmet. This then prevents it from being crafted again and so it may seems like it doesn't work, but it does.
Would you please test, the attached file (you have to use the .jar file inside the .zip file, github doesn'T allow the upload of .jar files directly), in your environment (probably the TownCraft modpack?), as fast as possible and let me know if it worked. After you feedback I would upload the fixed version to curseforge.
[FeederHelmet-1.10.2.zip](https://github.com/canitzp/FeederHelmet/files/6203516/FeederHelmet-1.10.2.zip)

**Comment by canitzp** [comment]
I've published the fixed file now, since I didn't want to wait longer. Please tell me if it fixes you problem

**Comment by ProsperCraft** [comment]
I will update and let you know thank you.

**Comment by canitzp** [comment]
@ProsperCraft is there any update?
