### ISSUE TITLE
Cannot put the auto feed module to dragon scale helmet of ice and fire 1.12

### ISSUE THREAD

**Issue by sosiskkkwkwwk** [canitzp/FeederHelmet#21]
There's no recipe of putting auto feed to my dragon scale helmet red...the only one that has a recipe was dragon scale helmet silver, and i already check jei if they can put auto feed on the dragon scale helmet..they did..but not the recipe of putting the module

**Comment by canitzp** [comment]
Hmm, I can take a look at the ice and fire mid, but your playing 1.12, which isn't supported by forge

**Comment by sosiskkkwkwwk** [comment]
That's a shame do you think i can fix that with crafTweaker.. i don't have experienced using craftTweaker so i little bit hesitant to use it

**Comment by canitzp** [comment]
Yeah you probably can fix it with crafttweaker
