### ISSUE TITLE
[1.16.5] Useless item visible in JEI: item.feederhelmet.photosynthesis_helmet_module

### ISSUE THREAD

**Issue by nerdywhiteguy** [canitzp/FeederHelmet#23]
This item has no texture, name, description, recipe, or uses.
Using FeederHelmet-1.10.2 and jei-1.16.5-7.7.0.106 (Minecraft 1.16.5 & Forge 36.1.10).
I tried adding your Solar Helmet mod, wondering if this was an optional dependency gone wrong, but the useless item remains.
![image](https://user-images.githubusercontent.com/1589227/123734161-aeb54d00-d851-11eb-8f55-19d39759aa7b.png)

**Comment by canitzp** [comment]
Well the photosynthesis module is an idea which I had previously and also I started to add it. It actually does nothing other than being an useless, uncraftable item.
The main idea is for the helmet to not need food at all. Instead like a solar, the helmet slowly fills up your hunger bar, when in contact with direct sunlight.
