### ISSUE TITLE
[Enhancement] Add configuration option: food_blacklist_smeltable = true

### ISSUE THREAD

**Issue by nerdywhiteguy** [canitzp/FeederHelmet#24]
When set to true, all food items with a smelting recipe should be automatically blacklisted.

While this can be achieved by manually adding every item to `food_blacklist`, this becomes difficult when using other mods that may add many food items.

Setting this to `true` by default also seems reasonable, as eating before smelting is typically a waste, and if you're *desperate* you can always eat food manually. But it seems like a conscious effort should be made to eat "raw" foods.

(And I second the suggestion to *at least* add `"minecraft:rotten_flesh"` to `food_blacklist` by default, à la #22.)

**Comment by canitzp** [comment]
The idea is good and I probably add something like this.

**Comment by canitzp** [comment]
@nerdywhiteguy can you write me on discord (canitzp#6125)? I want to know more about your modpack and how I can make this mod better

**Comment by canitzp** [comment]
@nerdywhiteguy Can you test this file and let me know if there are bugs?
(You have to rename it to .jar instead of .zip)
[FeederHelmet-1.11.0.zip](https://github.com/canitzp/FeederHelmet/files/6740508/FeederHelmet-1.11.0.zip)

**Comment by nerdywhiteguy** [comment]
Oh, sorry man. I wasn't paying attention to GitHub pings. I'm much more active on Discord, though, so… pings incoming. ^_^

**Comment by canitzp** [comment]
No problem ☺️
