### ISSUE TITLE
When eating fruit salad, return glass bottle instead of bowl

### ISSUE THREAD

**Issue by Simplebenja** [canitzp/FeederHelmet#27]
When the helmet consume a "Fruit salad" from Enhanced Farming (https://www.curseforge.com/minecraft/mc-mods/enhanced-farming) it return glass bottle instead of bowl, I don't know if it happens with other foods or mods
![image](https://user-images.githubusercontent.com/92282280/137767320-d709ad8b-298b-4706-8a0a-cf14bee381b3.png)

**Comment by Simplebenja** [comment]
Nevermind, is a bug of Enhanced Farming

**Comment by canitzp** [comment]
Okay thanks for letting me know
