### ISSUE TITLE
Bread?

### ISSUE THREAD

**Issue by somewhatfrog** [canitzp/FeederHelmet#28]
For some reason helmet avoids bread, I even added it into whitelist, but it didn't change anything. (1.18.1)

**Comment by canitzp** [comment]
So I just checked it and without any other mods installed, there is no issue with eating bread.

Can you please provide me some more information about your modpack, which helmet you're using?
Is the "Auto feeding mode" text displayed in the helmet tootlip?

**Comment by somewhatfrog** [comment]
Yes it is displayed on my iron helmet and it eats all cooked food + berries.
I have next mods:
axes are weapons
better third person
betterfpsdist
biomeinfo
chat heads
cloth config
compass coords
controllable
corpse
creative core
entity culling
fastleafdecay
ferrite core
fps reducer
goblin traders
guard villagers
jumpy boats
no telemetry
optifine
peacefulsurface
remove mouseover highlight
save your pets
simple inventory sorter
sit
villagers respawn mod

**Comment by canitzp** [comment]
So there is no obvious mod that could block bread from being eaten, so the only way to find out is for you to remove one mod after each other and check if the issue persits.

**Comment by somewhatfrog** [comment]
I see. If i will have time to do that, then i'll report results, but no idea how soon. I will close it for now, thank you!
