### ISSUE TITLE
Console errors regarding recipes

### ISSUE THREAD

**Issue by Dalethium** [canitzp/FeederHelmet#3]
I am not sure if this happens at late start up or at login, however these errors show up in the console 

```
Unidentified mapping from registry minecraft:recipes
    feederhelmet:feeder_item.peripheralsplusone:smart_helmet: 9045
    feederhelmet:feeder_item.cactusmod:cactushelmet: 9109
    feederhelmet:feeder_item.nex:armorhelmetbone: 9102
    feederhelmet:feeder_item.avaritia:infinity_helmet: 9018
    feederhelmet:feeder_item.shipwrecks_winslow:diving_helmet: 9108
    feederhelmet:feeder_item.nex:armorhelmethidesalamander: 9103
    peripheralsplusone:recipe_chunk_loader_tile.chickenchunks:chunk_loader|0: 14463
    thermaldynamics:cover: 11917
```
All lines are prefixed with: `[Netty Client IO #0/ERROR] [FML]:`

I do have all the mods listed there installed, if there's anything else you need just let me know!

**Comment by canitzp** [comment]
This is a bit strange. Can you post a log file and the Name if the Modpack you're playing?

**Comment by Dalethium** [comment]
Sure! It's called Convergence, I just play it with me and a couple friends (I put it together) you can play if you want ;) haha
[Log up until server log in](https://pastebin.com/BFnL78sr)
[Modlister mod list](https://www.modlister.com/user/Daleth)
[Modlister json output](https://pastebin.com/kfTyFGxf) (since this pack changes a lot)

The output in question is at line 18595, there's a LOT of output there we recently updated to 1.12 so there's still some bugs to work out. Sorry if it takes forever to load.
Here is a direct upload for you in case the pastebin page takes too long to load:
[BFnL78sr.txt](https://github.com/canitzp/FeederHelmet/files/1931127/BFnL78sr.txt)


Oh and I've only noticed this client side, however I don't read the server log as much so it could be there too idk.

Do you need anything else?

**Comment by canitzp** [comment]
No that is enough. I already know how I can fix this probably. One question, does the recipe for an AutoFeeding smart helmet work?

**Comment by Dalethium** [comment]
I'll check later today, sorry for the late reply!

**Comment by Dalethium** [comment]
the recipe works, but i can't take the smart feeding helmet out of the crafting table. 

like it shows the end item but i can't pull it out -- idk for sure but it seems like the client thinks it's a recipe but the server does not.

**Comment by canitzp** [comment]
but the mod is installed at the server? Does other helmets work?

**Comment by Dalethium** [comment]
yeah they do, i have it on my spectrite helmet.

**Comment by Dalethium** [comment]
Hey! So, I was going through my storage, and the feeding smart helmet did craft -- however it did not appear to craft at the time, it may have been some sort of desync error. I'll try to investigate further, sorry for taking so long!

**Comment by canitzp** [comment]
I'll close this for now. With the latest update it is possible to blacklist helmets to be craftable to FeederHelmets. You should consider doing this in you modpack if this error is getting more and more annoying
