### ISSUE TITLE
[Bug] Helmet doesn't take energy from Construct Armory's Fluxed/Energized Modifier

### ISSUE THREAD

**Issue by Desempregago** [canitzp/FeederHelmet#30]

**Comment by canitzp** [comment]
Can you show me the exact helmet used for this?

**Comment by Desempregago** [comment]
![2022-04-25_01 18 12](https://user-images.githubusercontent.com/14002834/165020163-9a67efc9-5eba-4544-8aec-98209ee154d5.png)
![2022-04-25_01 18 15](https://user-images.githubusercontent.com/14002834/165020168-a73a73c1-1a97-4d50-83d6-b4651162847a.png)

**Comment by Desempregago** [comment]
Neither durability nor energy gets consumed.

**Comment by canitzp** [comment]
Oh well it is draconic evolution again.
I fixed a issue with the wyvern armor before.
There is no "good" way for me fixing this issue and since you already have an unbreakable armor, you're probably pretty endgame, and so this issue is not crucial.
While reading the code I noticed that it "should" use up some energy from the helmet, but it isn't really noticeable and probably already refilled by the solar module.

**Comment by Desempregago** [comment]
the thing is, it happens even with other modules, like Fluxed Electrum, which also includes energy via the Energized trait.

**Comment by Desempregago** [comment]
it's not just Draconic. Also, the module BREAKS the helmet (the helmet item just vanishes), even if "durability necessary" is set to 1 (default config value) on Tinkers' Construct helmets (any helmet combination). It's probably bypassing the "broken" state of the helmet

**Comment by Desempregago** [comment]
>While reading the code I noticed that it "should" use up some energy from the helmet, but it isn't really noticeable and probably already refilled by the solar module.

It doesn't take energy, but also doesn't work (doesn't feed the player)

**Comment by canitzp** [comment]
Cloud you please provide the name of the modpack? It would make most sense, if I can test it there

**Comment by Desempregago** [comment]
It's a self made pack. I can send you the google drive link if you want

**Comment by Desempregago** [comment]
https://drive.google.com/file/d/1Puo1xtg6umXkLVGAMCwA6w4n23z4W3LT/view?usp=sharing

**Comment by canitzp** [comment]
Thank you for the link. I already tested the wyvern helmet and the feeding does infact work like it is designed. It does not work when the helmet is empty and it starts to work as soon as it has power. I also saw that it consume a little bit of energy, while consuming.

**Comment by Desempregago** [comment]
So it seems it's something on my end then?

**Comment by canitzp** [comment]
No it is not, I have found a problem with the energy handling. ConstructsArmory uses a different nbttag, when a "wyvern" armor is in use. Instead of "Energy" it is called "EvolvedEnergy". This of course can't be handled by the feeder module, leading to it not working at all.

**Comment by canitzp** [comment]
@Desempregago Please try this version out: https://filetransfer.io/data-package/AaEOUTQ2#link

**Comment by Desempregago** [comment]
It's perfect. Doesn't "void" (deletes) non-electric helmets anymore PLUS fixes the problem of not consuming energy. Many thanks :)

**Comment by Desempregago** [comment]
Found a bug:

https://user-images.githubusercontent.com/14002834/165076859-2a44fe64-e578-473b-8b0a-d87e6a368b3a.mp4

**Comment by Desempregago** [comment]
Happens with ANY helmet, doesn't need to be a Construct Armory helmet

**Comment by canitzp** [comment]
Oh well, I have fixed this issue in a newer mc version already

**Comment by canitzp** [comment]
@Desempregago try this one: https://filetransfer.io/data-package/ddMb3J9O#link

**Comment by Desempregago** [comment]
Will do later today. Thank you for your time.
