### ISSUE TITLE
Question: Disable or remove auto feeding module

### ISSUE THREAD

**Issue by Kangy1103** [canitzp/FeederHelmet#32]
Hi

Is there a way to disable or remove the auto feeding module from helmets?

Thanks in advance!

**Comment by canitzp** [comment]
There is currently no way to do that in survival. Do you have an idea on how to?

**Comment by Kangy1103** [comment]
Putting the helmet in a crafting grid to remove the module with a shapeless craft maybe? And/or a keybind to toggle the module on or off

**Comment by canitzp** [comment]
I think I'll go with the shapeless crafting, to uninstall the module
