### ISSUE TITLE
[1.20.1] Crash when loading game. (NoSuchFieldError: CREATIVE_MODE_TAB)

### ISSUE THREAD

**Issue by Gbergz** [canitzp/FeederHelmet#33]
## Title^

**MC:** 1.20.1
**Forge:** 47.0.19
**Auto Feeder Helmet:** 46.0.1 | https://www.curseforge.com/minecraft/mc-mods/auto-feeder-helmet/files/4600552

**Logs:** https://gist.githubusercontent.com/Gbergz/2b037f41db7bf697936f982e18097226/raw/1b67b543a9a6fbbcec4a71b1a17ae27f552199fa/gistfile1.txt

**Screenshots:**
![image](https://github.com/canitzp/FeederHelmet/assets/26634554/c2fed30c-9eaa-470d-95b1-82788f3fcc05)

**Notes:**
No additional mods added, only Forge(47.0.19) & Auto Feeder Helmet installed.

**-** Gbergz

**Comment by canitzp** [comment]
Thanks for reporting

**Comment by canitzp** [comment]
The bug ist fixed, but I'm not sure how this happened. I tested cross-version compatability before and it is fixed with just a recompile. New version 47.0.0 is released at curseforge and modrinth

**Comment by Gbergz** [comment]
Tried the update, doesn't work. Same error " `(NoSuchFieldError: CREATIVE_MODE_TAB)` "

**Comment by canitzp** [comment]
The f***, you are right. If I try the version from curse, it crashes. If I try my locally compiled one, it works.

**Comment by canitzp** [comment]
@Gbergz Please try the version from Modrinth. There it works: https://modrinth.com/mod/auto-feeder-helmet/versions

**Comment by Gbergz** [comment]
The .jar file from modrinth works and the game loads up like normal. No crashes.
However that isn't viable as I can't publish projects on CF with that version. 🤔

**Comment by Gbergz** [comment]
Also seems the recipes for any of the feeder helmets are not working.
![bild](https://github.com/canitzp/FeederHelmet/assets/26634554/768e9fa0-5286-4f4b-afa1-1452f28c557d)
![bild](https://github.com/canitzp/FeederHelmet/assets/26634554/b6b4266d-12f1-4188-b39c-1a832517effa)

**Comment by canitzp** [comment]
I'll fix the curseforge uploads as soon as possible, but probably not before next week.

To combine the module with the helmet, you need to use the smiting table (template slot is empty). JEI doesn't show this for some reason. Your first picture shows the removal of the module.

**Comment by Gbergz** [comment]
No worries.
and gotcha. Good to know.

**Comment by canitzp** [comment]
Correct versions uploaded to curseforge

**Comment by Gbergz** [comment]
Thanks it's working now with client, however when trying to join a server with the mod causes in instant disconnect.

Hope it's fine writing here instead of opening up a new issue.

part of logs: https://gist.githubusercontent.com/Gbergz/97484f21a8c8281d4b3693089e667ab0/raw/f5a515a72a0950d05dbacedcabf72da95218f501/gistfile1.txt

![screenshot](https://github.com/canitzp/FeederHelmet/assets/26634554/3cd5a966-2a8b-4ada-b121-f00aa2461ae4)

**Comment by canitzp** [comment]
oh man, always something to do. Can you please open a new issue for that?

**Comment by Gbergz** [comment]
yes I can.
