### ISSUE TITLE
Removes offhand item 

### ISSUE THREAD

**Issue by Jadan1213** [canitzp/FeederHelmet#36]
I've been running into an issue where my auto feeder will feed me and then the item i have in my offhand will get removed and put into my inventory.

MC 1.20.1
Forge 47.2.17

**Comment by canitzp** [comment]
This sounds extremely strange and something I never experienced.
Would you please provide a list of other mods installed or try to reproduce this issue without any other mods.

**Comment by Jadan1213** [comment]
If i had to guess, it might be stack refill by serilum mistakenly swapping the food into my offhand. I'll do some testing to try and narrow it down.

**Comment by canitzp** [comment]
Ok thank you for further testing

**Comment by Jadan1213** [comment]
> Ok thank you for further testing

I'm so sorry i never got back to you. I ended up removing "stack refill" and disabling quark's "auto tool replace" feature, and i haven't run into the issue since. So it was likely one of them causing it
